name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # o master, según tu repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: 1st-web  # Cambiá por el nombre de la carpeta que querés publicar

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
